# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.4
group=com.startraveler.bearminimum
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Bear Minimum
mod_author=Startraveler
mod_id=bearminimum
license=Apache 2.0
credits=Special thanks to Anatevka on the NeoForge Discord for suggesting the name!
description=A minimal mod that adds more bear varieties and rebalances polar bears.
minecraft_version_range=[1.20.1, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
